version: "3.8"

services:
  mlflow:
    build: .
    container_name: breast_cancer_mlflow
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://breast_cancer_mlflow:5001
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5001
    restart: always

  api:
    build: .
    container_name: breast_cancer_api
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MLFLOW_TRACKING_URI=http://breast_cancer_mlflow:5001  
    command: uvicorn src.inference_api:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  dashboard:
    build: .
    container_name: breast_cancer_dashboard
    depends_on:
      - mlflow
      - api
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_PORT=8501
      - MLFLOW_TRACKING_URI=http://breast_cancer_mlflow:5001
    command: streamlit run src/streamlit_dashboard.py --server.port 8501 --server.address 0.0.0.0
    restart: always
