version: "3.8"

services:
  api:
    build: .
    container_name: breast_cancer_api
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mlflow
    command: uvicorn src.inference_api:app --host 0.0.0.0 --port 8000

  dashboard:
    build: .
    container_name: breast_cancer_dashboard
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - api
      - mlflow
    command: streamlit run src/streamlit_dashboard.py --server.port 8501 --server.address 0.0.0.0

  mlflow:
    build: .
    container_name: breast_cancer_mlflow
    ports:
      - "5001:5001"
    restart: always
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5001

