apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-api-service
spec:
  selector:
    app: breast-cancer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
