name: Deploy ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python src/train_model.py

    - name: Build & Push Docker Image
      run: |
        docker build -t myregistry/breast-cancer-pipeline .
        docker push myregistry/breast-cancer-pipeline

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
